---

- name: "Ensure bind group '{{ bind__service_group }}' is present"
  group:
    name: '{{ bind__service_group }}'
    system: true
    state: present
  notify: ['restart-bind']

- name: "Ensure bind user '{{ bind__service_user }}' is present (first try)"
  user:
    name: '{{ bind__service_user }}'
    group: '{{ bind__service_group }}'
    shell: /bin/false
    createhome: false
    system: true
    state: present
  notify: ['restart-bind']

- name: Remove distribution specific directories
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ bind__remove_distribution_directories }}'

- name: Remove distribution specific files
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ bind__remove_distribution_files }}'

- name: Ensure bind read only configurations directories exists
  file:
    path: '{{ item }}'
    owner: root
    group: "{{ bind__service_group }}"
    mode: 0750
    state: directory
  with_items:
    - '{{ bind__config_directory }}'
    - '{{ bind__zones_directory }}'
    - '{{ bind__static_zones_directory }}'
    - '{{ bind__keys_directory }}'
    - '{{ bind__var_directory }}'

- name: Ensure bind read and write configurations directories exists
  file:
    path: '{{ item }}'
    owner: '{{ bind__service_user }}'
    group: '{{ bind__service_group }}'
    mode: 0770
    state: directory
  with_items:
    - '{{ bind__dynamic_zones_directory }}'
    - '{{ bind__managed_keys_directory }}'

- name: Ensure temporary data directory exists
  file:
    path: "{{ bind__var_data_directory }}"
    owner: "{{ bind__service_user }}"
    group: "{{ bind__service_group }}"
    mode: 0770
    state: directory

- name: Install bind service environment file
  template:
    src: bind.environment.j2
    dest: '{{ bind__service_environment }}'
    owner: root
    group: root
    mode: 0644
  when: bind__service_environment is defined
  notify: ['restart-bind']

- name: Import bind options configuration tasks
  import_tasks: configure-options.yml
  tags: ['bind', 'bind-configure-options']

- name: Import bind zones configuration tasks
  import_tasks: configure-zones.yml
  tags: ['bind', 'bind-configure-zones']
