---

# TODO to remove
- name: Remove bind.service systemd unit file
  file:
    path: '/etc/systemd/system/bind9.service'
    state: absent
  when: ansible_service_mgr == 'systemd'
  register: _bind__service_old
  notify: ['restart-bind']

- name: Ensure systemd override directory is created
  file:
    path: '/etc/systemd/system/{{ bind__service_name }}.service.d'
    state: directory
  when: ansible_service_mgr == 'systemd'

- name: Install systemd options override file
  template:
    src: systemd.service.d.j2
    dest: '/etc/systemd/system/{{ bind__service_name }}.service.d/ansible.conf'
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  register: _bind__service
  notify: ['restart-bind']

- name: Remove sysvinit unit file
  file:
    path: '{{ bind__service_sysvinit_script }}'
    state: absent
  when: ansible_service_mgr == 'systemd'
    and bind__service_sysvinit_script is defined
  register: _bind__sysvinit
  notify: ['restart-bind']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
    and (
      _bind__service is changed
      or _bind__sysvinit is changed
      or _bind__service_old is changed
    )

- name: Ensure bind is started and enabled on boot
  service:
    name: '{{ bind__service_name }}'
    enabled: '{{ bind__service_enabled|bool }}'
    state: "{{ bind__service_enabled|bool|ternary('started', 'stopped') }}"
